name: non-co2
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - nbstripout
#   - fair
  - matplotlib
  - numpy
#   - openpyxl
  - pandas
  - scipy
#   - seaborn
#   - statsmodels
  - tqdm
# if you need to pip install anything:
#   - pip
#   - pip:
#     - thing-to-pip-install
