name: non-co2
channels:
  - conda-forge
  - defaults
dependencies:
  - iris
  - jupyter
  - nbstripout
  - matplotlib
  - numpy
  - pandas
  - scipy
  - tqdm
# if you need to pip install anything:
#   - pip
#   - pip:
#     - thing-to-pip-install
